# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Negra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=12)),
                ('fecha_ingreso', models.DateTimeField()),
                ('razon_ingreso', models.CharField(max_length=320)),
                ('operadora', models.CharField(max_length=25)),
            ],
        ),
    ]
